version: '3'


services:
    nginx:
        restart: always
        image: nginx:latest
        expose:
          - 8080
        ports:
          - "80:8080"
        volumes:
            - ./project/logs:/srv/www/test_webim/logs
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - python
    python:
        restart: always
        build:
            context: .
            dockerfile: docker/python/Dockerfile
        volumes:
            - ./project:/srv/www/test_webim
        expose:
          - 8000
        ports:
            - 8000:8000
        command: "gunicorn -c gunicorn.py config.wsgi"
        env_file:
            ./.env